repository:
  name: nixing
  description: A place to collect things about Nix, it is also where to keep my dotfiles.
  homepage: https://brsvh.org/nixing
  topics: dotfiles, nix, flake
  private: true

  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
