{
  my,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    my.nixosProfiles.bash
    my.nixosProfiles.console
    my.nixosProfiles.disko
    my.nixosProfiles.english
    my.nixosProfiles.envvars
    my.nixosProfiles.facter
    my.nixosProfiles.firewall
    my.nixosProfiles.fish
    my.nixosProfiles.gnupg
    my.nixosProfiles.home-manager
    my.nixosProfiles.initrd
    my.nixosProfiles.kernel
    my.nixosProfiles.nix
    my.nixosProfiles.nixpkgs
    my.nixosProfiles.openssh
    my.nixosProfiles.polkit
    my.nixosProfiles.systemd-boot
    my.nixosProfiles.tools
    my.nixosProfiles.users
    my.nixosUsers.root
  ];
}
