name: Genreate Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ox-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout docs changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: shell
          filters: |
            org:
              - 'docs/README.org'

      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v14
        with:
          name: brsvh
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Export to Markdown
        id: export
        if: steps.changes.outputs.org == 'true'
        run: |
          for org in ${{ steps.changes.outputs.org_files }}
          do
             nix run github:brsvh/emacs.d#batch -- $org --funcall org-md-export-to-markdown
          done

      - name: Auto commit
        if: steps.export.outcome == 'success'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch --all
          git checkout -b auto-commit
          git add **/*.md
          git commit -m "docs: apply automatic changes"
          git push -v origin auto-commit\:main
